[package]
name = "blueprint-engine-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Starlark parser for Blueprint3"

[dependencies]
blueprint-engine-core.workspace = true
starlark.workspace = true
starlark_syntax.workspace = true
